[project]
name = "final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kagglehub>=0.3.11",
    "mediapipe==0.10.9",
    "numpy>=2.2.5",
    "opencv-python>=4.11.0.86",
]
