data:
  root: "data/raw/wlasl-complete"
  train_split: "nslt_2000.json"
  class_list: "data/raw/wlasl-complete/wlasl_class_list.txt"

  mode: "pose" # "vision" or "pose"
  video_path: "data/raw/wlasl-complete/videos"
  pose_path: "data/processed/landmarks"


train:
  batch_size: 32
  n_samples: 50 # only for pose
  num_copies: 4 # only for pose